FROM ubuntu:16.04
MAINTAINER mcano@mobicorp.com

WORKDIR /octo

ENV OCTO_VERSION=4.14.1

RUN curl -o OctopusTools.tar.gz https://download.octopusdeploy.com/octopus-tools/${OCTO_VERSION}/OctopusTools.${OCTO_VERSION}.ubuntu.16.04-x64.tar.gz && tar -xvzf OctopusTools.tar.gz && rm OctopusTools.tar.gz

CMD [ "./Octo" ]
